-- Add block support to questions table
ALTER TABLE public.questions
  ADD COLUMN IF NOT EXISTS block_id TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS instructions TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS paragraph TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS image_url TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS image_caption TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS block_order INT DEFAULT 0;
